name: CI

on: [push, pull_request]
jobs:
    build:
        name: "CI"
        runs-on: ubuntu-latest
        steps:
            - name: Get required pkgs
              run: |
                  sudo apt-get update
                  sudo apt-get install git golang make -y

            - name: Checkout source
              uses: actions/checkout@v3

            - name: Compile
              run: |
                  make

            - name: Tests and formatting checks
              run: |
                  make check
